### ISSUE TITLE
Allow users to view past theme reveals

### ISSUE THREAD

**Issue by Nirajn2311** [tedxnitksurathkal/tedxnitksurathkal.github.io#132]

**Comment by anirudhprabhakaran3** [comment]
Where can I find past theme releases?

**Comment by Nirajn2311** [comment]
For that you have to go through the repo history. Unfortunately, there is no tag to tell when the theme release was done so you'll mostly have to rely on the commit message and choose wisely.

Here are the two latest theme releases:

Pause to Play - https://github.com/tedxnitksurathkal/tedxnitksurathkal.github.io/tree/6b9de6850a99a0acfca1e314f35c34fe6e3b4609

Trailblazer - https://github.com/tedxnitksurathkal/tedxnitksurathkal.github.io/tree/6b9de6850a99a0acfca1e314f35c34fe6e3b4609
