### ISSUE TITLE
Home Page Speakers Styling

### ISSUE THREAD

**Issue by govindjeevan** [tedxnitksurathkal/tedxnitksurathkal.github.io#37]
![image](https://user-images.githubusercontent.com/23054200/66558328-00dfa780-eb71-11e9-935f-62842f7b2e52.png)
This could have better styling.

**Comment by nirmalhk7** [comment]
Sorry didn't get you. Better styling in what way?

**Comment by govindjeevan** [comment]
This is an image with a text at the bottom.
Has no styling at all. 

There is no uniformity in shape or size. There is no hover based action. Text should not just lie there like that, but should be encolsed in some card based layout.
Should use appropriate classes.
